### ISSUE TITLE
Installation steps ?

### ISSUE THREAD

**Issue by anubister** [molobrakos/tellsticknet#11]
Hello,
thanks for sharing this.
I discovered this is based on Docker; I tried a 'make' which made some compilation successfully but not the scripts/discover nor scripts/listen. Could you please provide some additional information on How to install / make it work ?
Thanks !

**Comment by molobrakos** [comment]
Docker is optional, you don't need to use it. How to make it work depends on what your use case is. Do you want to use it with Home Assistant?

**Comment by molobrakos** [comment]
Closing since no response for > 2 weeks. Please let me know how/if I can help. Best regards.

**Comment by ovelie** [comment]
I have the exact same problem!

Downloaded with git, and run Make with result:

  py37: commands succeeded
  congratulations :)

Trying to follow the "README.md" file but cant get the examples to work!

tellsticknet]# ./script/discover
-bash: ./script/discover: No such file or directory

I like to make this working with mqtt (working server on localhost) but last example gives me more errors. 
./script/tellsticknet mqtt -vv
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/tellsticknet/tellsticknet/__main__.py", line 27, in <module>
    import docopt
ModuleNotFoundError: No module named 'docopt'


isue 16 says ".... installed with pip ..." is this working or upcomming?

It would be great with a "install manual" in the readme file!

God jul, og godt nytt år!

**Comment by molobrakos** [comment]
What about
`pip install -r requirements.txt`
and then:
`./script/tellsticknet -vv discover`

I agree the instructions for installing/running could be improved. Feel free to contriubute a fix for this when you get it up and running.

`pip install tellsticknet` might work as well, but that version has not been updated for a while. I'll fix this in a couple of weeks.

**Comment by ovelie** [comment]
tried it:

# pip install -r requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting docopt (from -r requirements.txt (line 1))
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (40.4.3)
Collecting requests (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting pyyaml (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Collecting hbmqtt (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e6/3c/de08eeef75dc4bd86673f48ca4a97b51c9524cf2a32f1ef8ce0bfae81270/hbmqtt-0.9.5-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting transitions (from hbmqtt->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/14/4d/26043920085674539495eb3d80162a1ad3c749d2285b1151ab50a3259dc6/transitions-0.6.9-py2.py3-none-any.whl
Collecting websockets (from hbmqtt->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/4b/c6/026da2eeed75a49dd0b72a0c7ed6ee5cb2943e396ca9753eabff7359b27b/websockets-5.0.1.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-YD3MDN/websockets/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-YD3MDN/websockets/
# ./script/tellsticknet -vv discover
18-12-29 18:51.37 DEBUG (MainThread) [asyncio] Using selector: EpollSelector
18-12-29 18:51.37  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
18-12-29 18:51.37 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> <broadcast>:30303
18-12-29 18:51.37 DEBUG (MainThread) [tellsticknet.util] Sending packet to <broadcast>:30303
18-12-29 18:51.37 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 43276)>: b'D'
18-12-29 18:51.37 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 43276)>
18-12-29 18:51.37 DEBUG (MainThread) [tellsticknet.util] No data available on socket yet
18-12-29 18:51.42 DEBUG (MainThread) [tellsticknet.discovery] Discovery timeout
#
mvh
Ove

**Comment by molobrakos** [comment]
Sorry should have been `pip3 install --user -r requirements.txt`. Also, the discovery process doesn't seem to find any device on your local network.

**Comment by ovelie** [comment]
yes that worked! :-)

# ./script/tellsticknet -vv discover
18-12-29 19:22.04 DEBUG (MainThread) [asyncio] Using selector: EpollSelector
18-12-29 19:22.04  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
18-12-29 19:22.04 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> <broadcast>:30303
18-12-29 19:22.04 DEBUG (MainThread) [tellsticknet.util] Sending packet to <broadcast>:30303
18-12-29 19:22.04 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 46803)>: b'D'
18-12-29 19:22.04 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 46803)>
18-12-29 19:22.04 DEBUG (MainThread) [tellsticknet.util] No data available on socket yet
18-12-29 19:22.09 DEBUG (MainThread) [tellsticknet.discovery] Discovery timeout


I have 2 tellstick nett version 17 in my LAN (2 locations (Sweden and Norway)with openvpn)

Telldus-R1.Ende-Lie.no	192.168.82.223	Telldus Technologies AB	AC:CA:54:00:4A:E7
Telldus-B1.Ende-Lie.no	192.168.86.223	Telldus Technologies AB	AC:CA:54:00:8B:F8

**Comment by molobrakos** [comment]
Does your vpn route udp broadcast packets? You can provide a ip to the script to not rely on auto-discovery. However, only one tellstick is supported for each instance currently so I guess you then have to run two concurrently to e.g. use the mqtt gateway.

**Comment by ovelie** [comment]
Yes, my VPN is on an Ethernet bridge (layer 2) and open for all packets except dhcp answers!

Telldus-R1.Ende-Lie.no	192.168.82.223 is not on VPN but actually on my local LAN (192.168.80.0/21)

**Comment by molobrakos** [comment]
Your setup is too complex for the current version. :-) I think it only supports auto discovery on the same subnet. Feel free to contribute a change for this. Or skip the auto-discovery.

**Comment by ovelie** [comment]
I like the idea if "to complex" :-)

Kan you guide me to override the discovery, and putting data into "mqtt" ?

**Comment by molobrakos** [comment]
Try passing `-?` as argument

**Comment by ovelie** [comment]
--help is of course helpful!

I got data from "./script/tellsticknet --ip 192.168.82.223 -vv listen"  

thanks a lot for your updates!

Ha en fortsatt fredfull jul og et godt nytt år!

**Comment by ovelie** [comment]
Godt nytt år!

Then I got things up and running and can use information from mqtt in node red for automating my switches, mostly lightning, based on the information i get from my motion sensors!

This is perfect for getting information from my sensors and is instant update instead of 30+ seconds later. When I got this working I realy got frustrated when I still got 15+ seconds from sending "light / switch on" using Teldus live service.

I found your comment on how to use command line to get my switch turning in my test lamp, and it successfully turn on/off !

# /root/tellsticknet/script/tellsticknet --ip 192.168.82.223 -vv send RLS_Taklmape_stearinlys off
19-01-02 18:10.04 DEBUG (MainThread) [asyncio] Using selector: EpollSelector
19-01-02 18:10.04 DEBUG (MainThread) [__main__] checking for config file /root/tellsticknet/tellsticknet/tellsticknet.conf
19-01-02 18:10.04  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:30303
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:30303
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 59295)>: b'D'
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 59295)>
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] No data available on socket yet
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Data available on socket
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 59295)>
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Got data from sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 59295)>: (b'TellStickNet:ACCA54004AE7:PC6F2CPLZY:17', ('192.168.82.223', 30303))
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.discovery] Got b'TellStickNet:ACCA54004AE7:PC6F2CPLZY:17' from 192.168.82.223:30303
19-01-02 18:10.04  INFO (MainThread) [tellsticknet.discovery] Found TellStickNet device with firmware 17 at 192.168.82.223
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Created controller: Controller@192.168.82.223 (acca54004ae7)
19-01-02 18:10.04  INFO (MainThread) [__main__] Found controller: Controller@192.168.82.223 (acca54004ae7)
19-01-02 18:10.04  INFO (MainThread) [__main__] Executing for 1 devices
19-01-02 18:10.04 DEBUG (MainThread) [__main__] Waiting for tasks to finish
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Sending time 1 of 2
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.protocol] Encoding for protocol arctech
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Sending packet to controller ('192.168.82.223', 42314) <b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi2ss'>
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:42314
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:42314
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 40174)>: b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi2ss'
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Waiting 1 seconds
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Sending time 2 of 2
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.protocol] Encoding for protocol arctech
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.controller] Sending packet to controller ('192.168.82.223', 42314) <b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi2ss'>
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:42314
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:42314
19-01-02 18:10.04 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 40634)>: b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi2ss'

# /root/tellsticknet/script/tellsticknet --ip 192.168.82.223 -vv send RLS_Taklmape_stearinlys on
19-01-02 18:10.07 DEBUG (MainThread) [asyncio] Using selector: EpollSelector
19-01-02 18:10.07 DEBUG (MainThread) [__main__] checking for config file /root/tellsticknet/tellsticknet/tellsticknet.conf
19-01-02 18:10.07  INFO (MainThread) [tellsticknet.discovery] Discovering tellstick devices ...
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:30303
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:30303
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 45885)>: b'D'
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 45885)>
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] No data available on socket yet
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Data available on socket
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Reading from <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 45885)>
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Got data from sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 45885)>: (b'TellStickNet:ACCA54004AE7:PC6F2CPLZY:17', ('192.168.82.223', 30303))
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.discovery] Got b'TellStickNet:ACCA54004AE7:PC6F2CPLZY:17' from 192.168.82.223:30303
19-01-02 18:10.07  INFO (MainThread) [tellsticknet.discovery] Found TellStickNet device with firmware 17 at 192.168.82.223
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Created controller: Controller@192.168.82.223 (acca54004ae7)
19-01-02 18:10.07  INFO (MainThread) [__main__] Found controller: Controller@192.168.82.223 (acca54004ae7)
19-01-02 18:10.07  INFO (MainThread) [__main__] Executing for 1 devices
19-01-02 18:10.07 DEBUG (MainThread) [__main__] Waiting for tasks to finish
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Sending time 1 of 2
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.protocol] Encoding for protocol arctech
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Sending packet to controller ('192.168.82.223', 42314) <b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi1ss'>
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:42314
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:42314
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 36712)>: b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi1ss'
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Waiting 1 seconds
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Sending time 2 of 2
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.protocol] Encoding for protocol arctech
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.controller] Sending packet to controller ('192.168.82.223', 42314) <b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi1ss'>
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)> 192.168.82.223:42314
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Sending packet to 192.168.82.223:42314
19-01-02 18:10.07 DEBUG (MainThread) [tellsticknet.util] Wrote data to sock <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 45378)>: b'4:sendh8:protocol7:arctech5:modelC:selflearning5:housei1040e25s4:uniti0s6:methodi1ss'

part of my tellsticknet.conf

----------------------------
name: FKR_1_2
component: remote
protocol: arctech
model: selflearning
unit: 2
house: 11315622
optimistic: true
---
name: RLS_Taklmape_stearinlys
component: light
protocol: arctech
model: selflearning
unit: 1
house: 17042981
----------------------------

I tried to check information i got from my sensors and I get information like this example:
tellsticknet/ACCA54004AE7/command/remote/fkr_1_2/state turnoff

I tried to build several lookalike message and now last successfully injected:
tellsticknet/ACCA54004AE7/command/light/rls_taklmape_stearinlys/state turnon

And nothing happens :-(

Can you please help me with a (hopefully for this lamp) mqtt syntax, that wil turn on/off and I can use as a base to build the rest on?

**Comment by molobrakos** [comment]
I don't have access to my setup currently, but look for `command_topic` under `homeassistant/#` (this should probably be configurable) for your particular device (`rls_taklampe`), as well as `payload_on/off`.

**Comment by ovelie** [comment]
Yes, you managed to guide me in the right direction:

Listening to raw mqtt packages at my "mossquit" server I got the config message:

homeassistant/light/tellsticknet_ACCA54004AE7/command_light_rls_taklmape_stearinlys/config {
	"name": "RLS_Taklmape_stearinlys",
	"state_topic": "tellsticknet/ACCA54004AE7/command/light/rls_taklmape_stearinlys/state",
	"retain": true,
	"availability_topic": "tellsticknet/ACCA54004AE7/command/light/rls_taklmape_stearinlys/avail",
	"payload_available": "online",
	"payload_not_available": "offline",
	"command_topic": "tellsticknet/ACCA54004AE7/command/light/rls_taklmape_stearinlys/set",
	"optimistic": true,
	"payload_on": "turnon",
	"payload_off": "turnoff"}

So sending topic: "tellsticknet/ACCA54004AE7/command/light/rls_taklmape_stearinlys/set" payload: "turnon" / "turnoff" it worked!

Thanks a lot for your help!
