### ISSUE TITLE
Start problems

### ISSUE THREAD

**Issue by Gohper** [molobrakos/tellsticknet#19]
Whatever I do, i'm getting:
`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mqtt/tellsticknet/tellsticknet/__main__.py", line 96
    prepend_timestamp(packet) async for packet in controller.packets()
                                  ^
SyntaxError: invalid syntax`

Am I missing something?

Regards

**Comment by Gohper** [comment]
Oh, saw in the code that python 3.7 is needed...

**Comment by Gohper** [comment]
Did not help...

**Comment by Gohper** [comment]
Progress..., installed a release, two days old. Now it starts, it also discovers my TS net (v1).

Now, where do i put the config file..., /etc? Filename tellsticknet.conf?

This will be nice to bypass Teldus Live..., so slow, and remote controls channels are not On or Off, mostly they are idle...

**Comment by Gohper** [comment]
Ahh, thank you for a quick response!!

I got it working now, connecting with the Home Assistant, so far it looks great!
The problem I have with TL is, except that it is slow, remotes and wall switches (aka remote).
They are normally IDLE and only momentary On or OFF.

I will see if I will have the time to learn python and contribute, I have some ideas that might be nice.

First I need to learn HA, only used it for a week! So far so good!

R
