### ISSUE TITLE
Error in packet parsing

### ISSUE THREAD

**Issue by christer** [molobrakos/tellsticknet#6]
Got a remote with three on/off pairs and a all on/off pair.

pair one and the all pair works, the other two causes an AttributeError:
this is a working on button press:

```
DEBUG:tellsticknet.controller:Listening for signals from 10.0.0.13
INFO:tellsticknet.controller:Registering self as listener for device at 10.0.0.13
DEBUG:tellsticknet.controller:Sending packet to controller 10.0.0.13:42314 <b'b:reglistener'>
DEBUG:tellsticknet.controller:Got packet {'house': 40037358, 'group': 0, 'class': 'command', 'method': 'turnon', 'unit': 16, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('unit', 16), ('house', 40037358)})
DEBUG:tellsticknet.controller:Returning packet {'house': 40037358, 'group': 0, 'class': 'command', 'method': 'turnon', 'unit': 16, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Got packet {'house': 11966, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 11966), ('unit', 4)})
DEBUG:tellsticknet.controller:Returning packet {'house': 11966, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
DEBUG:tellsticknet.controller:Got packet {'house': 62521022, 'group': 1, 'class': 'command', 'method': 'turnon', 'unit': 10, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 62521022), ('unit', 10)})
DEBUG:tellsticknet.controller:Returning packet {'house': 62521022, 'group': 1, 'class': 'command', 'method': 'turnon', 'unit': 10, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Got packet {'house': 16062, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 16062), ('unit', 4)})
DEBUG:tellsticknet.controller:Returning packet {'house': 16062, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
DEBUG:tellsticknet.controller:Got packet {'house': 65961662, 'group': 1, 'class': 'command', 'method': 'turnon', 'unit': 10, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 65961662), ('unit', 10)})
DEBUG:tellsticknet.controller:Returning packet {'house': 65961662, 'group': 1, 'class': 'command', 'method': 'turnon', 'unit': 10, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 65961662), ('unit', 10)})
DEBUG:tellsticknet.controller:Returning packet {'house': 65961662, 'group': 1, 'class': 'command', 'method': 'turnon', 'unit': 10, 'lastUpdated': 1475958431, 'model': 'selflearning', 'protocol': 'arctech'}
DEBUG:tellsticknet.controller:Got packet {'house': 16062, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
DEBUG:tellsticknet.controller:Updated state for contoller
DEBUG:tellsticknet.controller:Updated state for contoller frozenset({('house', 16062), ('unit', 4)})
DEBUG:tellsticknet.controller:Returning packet {'house': 16062, 'protocol': 'everflourish', 'method': 'turnon', 'unit': 4, 'lastUpdated': 1475958431, 'class': 'command', 'model': 'selflearning'}
```

This is the second on buttonV

```
DEBUG:tellsticknet.controller:creating controller with address 10.0.0.13
DEBUG:tellsticknet.controller:Listening for signals from 10.0.0.13
INFO:tellsticknet.controller:Registering self as listener for device at 10.0.0.13
DEBUG:tellsticknet.controller:Sending packet to controller 10.0.0.13:42314 <b'b:reglistener'>
DEBUG:tellsticknet.controller:Got packet {'protocol': 'arctech', 'group': 0, 'unit': 16, 'model': 'selflearning', 'lastUpdated': 1475958636, 'method': 'turnoff', 'house': 20018679, 'class': 'command'}
DEBUG:tellsticknet.controller:Updated state for contoller
INFO:tellsticknet.controller:Discovered new controller frozenset({('house', 20018679), ('unit', 16)})
DEBUG:tellsticknet.controller:Returning packet {'protocol': 'arctech', 'group': 0, 'unit': 16, 'model': 'selflearning', 'lastUpdated':
1475958636, 'method': 'turnoff', 'house': 20018679, 'class': 'command'}
DEBUG:tellsticknet.protocols.everflourish:Not Everflourish (data=bafb9e, house=11966, unit=4, method=14)
Traceback (most recent call last):
  File "./telldus_mqtt_proxy.py", line 68, in <module>
    main()
  File "./telldus_mqtt_proxy.py", line 62, in main
    for packet in controller.events():
  File "/home/hcs/.virtualenvs/telldus_mqtt_proxy/lib/python3.5/site-packages/tellsticknet/controller.py", line 102, in events
    packet.update(lastUpdated=int(time()))
AttributeError: 'NoneType' object has no attribute 'update'
```

My hope is not so much a fix parser of the specific parser as a fix so that the parser doesn't raise a exception on failure.

**Comment by molobrakos** [comment]
Can you try to add:
```
if packet is None:
    continue  # invalid packet
```
just before line 102 in `tellsticknet/controller.py`

(Unfortunately I am currently away from the network where my Tellstick Net device is located)

**Comment by molobrakos** [comment]
Maybe closed by https://github.com/molobrakos/tellsticknet/pull/8 ?
